/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
//Parte 1 - Encontrar a sequência de Fibonacci até 4 milhões
//Parte 2 - Percorrer a sequência encontrada encontrando os números pares
//Parte 3 - Somar os números

var array = [1, 2];
var valor = 3;

while (valor <= 4000000) {
    array.push(valor);
    var tamanho = array.length - 1;
    var penultimaPosicao = array.length - 2;
    valor = array[tamanho] + array[penultimaPosicao]
}

//console.log(array)

var somaTotal = 0
for (var i = 0; i < array.length; i++) {
    if ( array[i] % 2 === 0) {
        somaTotal += array[i]
    }
}
console.log(somaTotal)